#! /bin/sh

##  Startup
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
picom -f &
nitrogen --restore &
xrandr --auto --output HDMI1 --mode 1920x1080 --left-of DP3 &
xsetroot -cursor_name left_ptr &
setxkbmap us &

##  Tags
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX
#bspc monitor DP3 -d I II III IV V VI VII VIII IX

##  Looks
bspc config border_width        1 
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##    Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
